feat(workflow): add `cargosort` workflow

diff --git a/.github/workflows/_rust_lints.yml b/.github/workflows/_rust_lints.yml
--- a/.github/workflows/_rust_lints.yml
+++ b/.github/workflows/_rust_lints.yml
@@ -26,6 +26,23 @@ jobs:
         run: rustup toolchain install nightly --component rustfmt --allow-downgrade
       - name: Check Rust formatting
         run: cargo +nightly ci-fmt
+  
+  cargosort:
+    if: (!cancelled() && inputs.isRust)
+    runs-on: [self-hosted]
+    steps:
+      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
+      - name: Check Cargo.toml format and sorting
+        run: python scripts/cargo_sort/cargo_sort.py
+      - name: Check Cargo.toml diffs after formatting
+        uses: technote-space/get-diff-action/@f27caffdd0fb9b13f4fc191c016bb4e0632844af # pin@v6.1.2
+        with:
+          FILES: Cargo.toml
+      - run: |
+          echo "Cargo.toml files have been modified!"
+          exit 1
+        # Fail only if there are differences in the repository
+        if: env.GIT_DIFF && env.MATCHED_FILES
 
   clippy:
     if: (!cancelled() && !failure() && inputs.isRust)
