come on

diff --git a/.github/workflows/cargo_llvm_cov.yml b/.github/workflows/cargo_llvm_cov.yml
--- a/.github/workflows/cargo_llvm_cov.yml
+++ b/.github/workflows/cargo_llvm_cov.yml
@@ -67,7 +67,6 @@ jobs:
             --failure-mode=warn \
             --sparse \
             --output target/nextest.profdata
-          set -e
 
           if [ $? -ne 0 ]; then
             echo "Error detected despite `--ignore-run-fail`. Trying to salvage the situation:"
@@ -95,7 +94,29 @@ jobs:
 
           set +e
           ./scripts/simtest/simtest-cov.sh
-          set -e
+
+          find target/llvm-cov-target -name '*.profraw' -print0 | xargs -0 $LLVM_PROFDATA merge \
+            --failure-mode=warn \
+            --sparse \
+            --output target/simtest.profdata
+
+          if [ $? -ne 0 ]; then
+            echo "Error detected despite `--ignore-run-fail`. Trying to salvage the situation:"
+            echo "Scanning for corrupted .profraw files. This might take a while."
+            find target/llvm-cov-target -name '*.profraw' | while read file; do
+              if ! "$LLVM_PROFDATA" show "$file" > /dev/null 2>&1; then
+                echo "$file: corruped -> removing"
+                rm "$file"
+              else
+                echo "$file: good"
+              fi
+            done
+
+            find target/llvm-cov-target -name '*.profraw' -print0 | xargs -0 $LLVM_PROFDATA merge \
+              --failure-mode=warn \
+              --sparse \
+              --output target/simtest.profdata
+          fi
 
           if [ ! -s "target/simtest.profdata" ]; then
             echo "🚨 Warning 🚨: Collecting simtest coverage failed." 
