failsafe for releases in non-releases branches

diff --git a/.github/workflows/changesets_publish.yml b/.github/workflows/changesets_publish.yml
--- a/.github/workflows/changesets_publish.yml
+++ b/.github/workflows/changesets_publish.yml
@@ -28,6 +28,14 @@ jobs:
   publish:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate branch
+        if: github.event.inputs.release_type != 'experimental'
+        run: |
+          if [[ ! "${{ github.ref_name }}" == releases/* ]]; then
+            echo "::error::The '${{ github.event.inputs.release_type }}' release type can only be run from a branch starting with 'release/'"
+            exit 1
+          fi
+
       - name: checkout code repository
         uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
         with:
