temp for testing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -39,170 +39,170 @@ env:
   TMP_BUILD_DIR: "./tmp/release"
 
 jobs:
-  release-build:
-    name: Build & Publish Binaries
-    timeout-minutes: 240
-    strategy:
-      matrix:
-        os: [
-          self-hosted, # ubuntu-x86_64
-          ubuntu-24.04-arm,
-          macos-latest, # macos-arm64
-          windows-latest, # windows-x86_64
-        ]
-      fail-fast: false
-    runs-on: ${{ matrix.os }}
-    steps:
-      - name: Clean up and validate ${{ env.TAG_NAME }} tag name
-        shell: bash
-        run: |
-          export iota_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'// )
-          [[ "${iota_tag}" == "develop" ]] && echo "tag cannot be equal to 'develop'" && exit 1
-          echo "iota_tag=${iota_tag}" >> $GITHUB_ENV
-          export iota_version=$(echo ${iota_tag} | sed -e 's/mainnet-v//' -e 's/testnet-v//')
-          echo "iota_version=${iota_version}" >> $GITHUB_ENV
+  # release-build:
+  #   name: Build & Publish Binaries
+  #   timeout-minutes: 240
+  #   strategy:
+  #     matrix:
+  #       os: [
+  #         self-hosted, # ubuntu-x86_64
+  #         ubuntu-24.04-arm,
+  #         macos-latest, # macos-arm64
+  #         windows-latest, # windows-x86_64
+  #       ]
+  #     fail-fast: false
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #     - name: Clean up and validate ${{ env.TAG_NAME }} tag name
+  #       shell: bash
+  #       run: |
+  #         export iota_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'// )
+  #         [[ "${iota_tag}" == "develop" ]] && echo "tag cannot be equal to 'develop'" && exit 1
+  #         echo "iota_tag=${iota_tag}" >> $GITHUB_ENV
+  #         export iota_version=$(echo ${iota_tag} | sed -e 's/mainnet-v//' -e 's/testnet-v//')
+  #         echo "iota_version=${iota_version}" >> $GITHUB_ENV
 
-      - name: Check out ${{ env.iota_tag }}
-        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
-        with:
-          ref: ${{ env.iota_tag }}
+  #     - name: Check out ${{ env.iota_tag }}
+  #       uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
+  #       with:
+  #         ref: ${{ env.iota_tag }}
 
-      - name: Set os/arch variables (Windows)
-        if: ${{ matrix.os == 'windows-latest' }}
-        shell: bash
-        run: |
-          export arch=$(uname -m)
-          export os_type="windows-${arch}"
-          echo "os_type=${os_type}" >> $GITHUB_ENV
-          echo "extention=$(echo ".exe")" >> $GITHUB_ENV
+  #     - name: Set os/arch variables (Windows)
+  #       if: ${{ matrix.os == 'windows-latest' }}
+  #       shell: bash
+  #       run: |
+  #         export arch=$(uname -m)
+  #         export os_type="windows-${arch}"
+  #         echo "os_type=${os_type}" >> $GITHUB_ENV
+  #         echo "extention=$(echo ".exe")" >> $GITHUB_ENV
 
-      - name: Set os/arch variables (Ubuntu)
-        if: ${{ matrix.os == 'self-hosted' || matrix.os == 'ubuntu-24.04-arm' }}
-        shell: bash
-        run: |
-          export arch=$(uname -m)
-          export os_type="linux-${arch}"
-          echo "os_type=${os_type}" >> $GITHUB_ENV
+  #     - name: Set os/arch variables (Ubuntu)
+  #       if: ${{ matrix.os == 'self-hosted' || matrix.os == 'ubuntu-24.04-arm' }}
+  #       shell: bash
+  #       run: |
+  #         export arch=$(uname -m)
+  #         export os_type="linux-${arch}"
+  #         echo "os_type=${os_type}" >> $GITHUB_ENV
 
-      - name: Set os/arch variables (MacOS)
-        if: ${{ matrix.os == 'macos-latest' }}
-        shell: bash
-        run: |
-          export arch=$(uname -m)
-          export system_os=$(echo ${{ matrix.os }} | cut -d- -f1)
-          export os_type="${system_os}-${arch}"
-          echo "os_type=${system_os}-${arch}" >> $GITHUB_ENV
+  #     - name: Set os/arch variables (MacOS)
+  #       if: ${{ matrix.os == 'macos-latest' }}
+  #       shell: bash
+  #       run: |
+  #         export arch=$(uname -m)
+  #         export system_os=$(echo ${{ matrix.os }} | cut -d- -f1)
+  #         export os_type="${system_os}-${arch}"
+  #         echo "os_type=${system_os}-${arch}" >> $GITHUB_ENV
 
-      - name: Setup caching
-        # Fork of 'Swatinem/rust-cache' which allows caching additional paths
-        uses: bmwill/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0
+  #     - name: Setup caching
+  #       # Fork of 'Swatinem/rust-cache' which allows caching additional paths
+  #       uses: bmwill/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0
 
-      - name: Install nexttest (Windows)
-        if: ${{ matrix.os == 'windows-latest' }}
-        uses: taiki-e/install-action@375e0c7f08a66b8c2ba7e7eef31a6f91043a81b0 # v2.44.38
-        with:
-          tool: nextest
+  #     - name: Install nexttest (Windows)
+  #       if: ${{ matrix.os == 'windows-latest' }}
+  #       uses: taiki-e/install-action@375e0c7f08a66b8c2ba7e7eef31a6f91043a81b0 # v2.44.38
+  #       with:
+  #         tool: nextest
 
-      - name: Install postgres (Windows)
-        if: ${{ matrix.os == 'windows-latest' }}
-        shell: bash
-        run: |
-          choco install postgresql16 --force --params '/Password:root'
-          echo "C:\Program Files\PostgreSQL\16\bin" >> $GITHUB_PATH
-          echo "C:\Program Files\PostgreSQL\16\lib" >> $GITHUB_PATH
-          echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\16\lib" >> $GITHUB_ENV
-          echo "PG_DATABASE_URL=postgres://postgres:root@localhost/" >> $GITHUB_ENV
-          echo "PG_EXAMPLE_DATABASE_URL=postgres://postgres:root@localhost/diesel_example" >> $GITHUB_ENV
+  #     - name: Install postgres (Windows)
+  #       if: ${{ matrix.os == 'windows-latest' }}
+  #       shell: bash
+  #       run: |
+  #         choco install postgresql16 --force --params '/Password:root'
+  #         echo "C:\Program Files\PostgreSQL\16\bin" >> $GITHUB_PATH
+  #         echo "C:\Program Files\PostgreSQL\16\lib" >> $GITHUB_PATH
+  #         echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\16\lib" >> $GITHUB_ENV
+  #         echo "PG_DATABASE_URL=postgres://postgres:root@localhost/" >> $GITHUB_ENV
+  #         echo "PG_EXAMPLE_DATABASE_URL=postgres://postgres:root@localhost/diesel_example" >> $GITHUB_ENV
 
-      - name: Install postgres (MacOS arm64)
-        if: ${{ matrix.os == 'macos-latest' }}
-        shell: bash
-        env:
-          PQ_LIB_DIR: "$(brew --prefix libpq)/lib"
-          LIBRARY_PATH: "/opt/homebrew/lib:$LIBRARY_PATH"
-          PKG_CONFIG_PATH: "/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH"
-          PATH: "/opt/homebrew/bin:$PATH"
-        run: |
-          brew install postgresql
+  #     - name: Install postgres (MacOS arm64)
+  #       if: ${{ matrix.os == 'macos-latest' }}
+  #       shell: bash
+  #       env:
+  #         PQ_LIB_DIR: "$(brew --prefix libpq)/lib"
+  #         LIBRARY_PATH: "/opt/homebrew/lib:$LIBRARY_PATH"
+  #         PKG_CONFIG_PATH: "/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH"
+  #         PATH: "/opt/homebrew/bin:$PATH"
+  #       run: |
+  #         brew install postgresql
 
-      #  NOTE: Self-hosted runners should already have postgres installed
-      - name: Install postgres (Ubuntu arm64)
-        if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
-        shell: bash
-        run: |
-          sudo apt install libpq-dev
+  #     #  NOTE: Self-hosted runners should already have postgres installed
+  #     - name: Install postgres (Ubuntu arm64)
+  #       if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
+  #       shell: bash
+  #       run: |
+  #         sudo apt install libpq-dev
 
-      - name: Remove unused apps (MacOS arm64)
-        if: ${{ matrix.os == 'macos-latest' }}
-        continue-on-error: true
-        shell: bash
-        run: |
-          # MacOS arm64 runner only has 14GB avaialble, which is too small for our builds, so removing unused softwared.
-          df -h /
-          sudo rm -rf /Applications/Xcode*.app
-          sudo rm -rf ~/Library/Developer/Xcode/DerivedData
-          sudo rm -rf ~/Library/Developer/CoreSimulator/Caches/*
-          sudo rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport/*
-          df -h /
+  #     - name: Remove unused apps (MacOS arm64)
+  #       if: ${{ matrix.os == 'macos-latest' }}
+  #       continue-on-error: true
+  #       shell: bash
+  #       run: |
+  #         # MacOS arm64 runner only has 14GB avaialble, which is too small for our builds, so removing unused softwared.
+  #         df -h /
+  #         sudo rm -rf /Applications/Xcode*.app
+  #         sudo rm -rf ~/Library/Developer/Xcode/DerivedData
+  #         sudo rm -rf ~/Library/Developer/CoreSimulator/Caches/*
+  #         sudo rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport/*
+  #         df -h /
 
-      - name: Cargo build for ${{ matrix.os }} platform
-        shell: bash
-        # Currently building in release mode, but we could also have debug builds for testing
-        run: |
-          [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release --features indexer
+  #     - name: Cargo build for ${{ matrix.os }} platform
+  #       shell: bash
+  #       # Currently building in release mode, but we could also have debug builds for testing
+  #       run: |
+  #         [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release --features indexer
 
-      - name: Rename binaries for ${{ matrix.os }}
-        shell: bash
-        run: |
-          mkdir -p ${{ env.TMP_BUILD_DIR }}
+  #     - name: Rename binaries for ${{ matrix.os }}
+  #       shell: bash
+  #       run: |
+  #         mkdir -p ${{ env.TMP_BUILD_DIR }}
 
-          [ ! -f ${{ env.BINARY_LIST_FILE }} ] && echo "${{ env.BINARY_LIST_FILE }} cannot be found" && exit 1
-          for binary in $(cat ${{ env.BINARY_LIST_FILE }} | jq -r '.release_binaries[]'); do
-            export binary=$(echo ${binary} | tr -d $'\r')
-            mv ./target/release/${binary}${{ env.extention }} ${{ env.TMP_BUILD_DIR }}/${binary}${{ env.extention }}
-          done
+  #         [ ! -f ${{ env.BINARY_LIST_FILE }} ] && echo "${{ env.BINARY_LIST_FILE }} cannot be found" && exit 1
+  #         for binary in $(cat ${{ env.BINARY_LIST_FILE }} | jq -r '.release_binaries[]'); do
+  #           export binary=$(echo ${binary} | tr -d $'\r')
+  #           mv ./target/release/${binary}${{ env.extention }} ${{ env.TMP_BUILD_DIR }}/${binary}${{ env.extention }}
+  #         done
 
-          tar -cvzf ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz -C ${{ env.TMP_BUILD_DIR }} .
+  #         tar -cvzf ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz -C ${{ env.TMP_BUILD_DIR }} .
 
-      #      - name: Publish Windows iota binary to Chocolatey
-      #        if: ${{ matrix.os == 'windows-latest' && contains(env.iota_tag, 'testnet') }}
-      #        shell: bash
-      #        run: |
-      #          choco install checksum
-      #          export iota_sha=$(checksum -t sha256 ${{ env.TMP_BUILD_DIR }}/iota.exe)
-      #          cd chocolatey
-      #
-      #          cat <<EOF >>VERIFICATION.txt
-      #          IOTA Binary verification steps
-      #          1. Download https://github.com/iotaledger/iota/releases/download/${{ env.iota_tag }}/iota-${{ env.iota_tag }}-windows-x86_64.tgz
-      #          2. Extract iota.exe
-      #          3. Verify binary: checksum.exe -t sha256 iota.exe: ${iota_sha}
-      #
-      #          File 'LICENSE.txt' is obtained from: https://github.com/iotaledger/iota/blob/develop/LICENSE
-      #          EOF
-      #
-      #          choco pack --version ${{ env.iota_version }} configuration=release
-      #          choco apikey --api-key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
-      #          choco push iota.${{ env.iota_version }}.nupkg --source https://push.chocolatey.org/
+  #     #      - name: Publish Windows iota binary to Chocolatey
+  #     #        if: ${{ matrix.os == 'windows-latest' && contains(env.iota_tag, 'testnet') }}
+  #     #        shell: bash
+  #     #        run: |
+  #     #          choco install checksum
+  #     #          export iota_sha=$(checksum -t sha256 ${{ env.TMP_BUILD_DIR }}/iota.exe)
+  #     #          cd chocolatey
+  #     #
+  #     #          cat <<EOF >>VERIFICATION.txt
+  #     #          IOTA Binary verification steps
+  #     #          1. Download https://github.com/iotaledger/iota/releases/download/${{ env.iota_tag }}/iota-${{ env.iota_tag }}-windows-x86_64.tgz
+  #     #          2. Extract iota.exe
+  #     #          3. Verify binary: checksum.exe -t sha256 iota.exe: ${iota_sha}
+  #     #
+  #     #          File 'LICENSE.txt' is obtained from: https://github.com/iotaledger/iota/blob/develop/LICENSE
+  #     #          EOF
+  #     #
+  #     #          choco pack --version ${{ env.iota_version }} configuration=release
+  #     #          choco apikey --api-key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
+  #     #          choco push iota.${{ env.iota_version }}.nupkg --source https://push.chocolatey.org/
 
-      - name: Upload release artifacts for ${{ matrix.os }} platform
-        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
-        with:
-          name: iota-binaries-${{ matrix.os }}
-          if-no-files-found: error
-          path: |
-            ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz
+  #     - name: Upload release artifacts for ${{ matrix.os }} platform
+  #       uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
+  #       with:
+  #         name: iota-binaries-${{ matrix.os }}
+  #         if-no-files-found: error
+  #         path: |
+  #           ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz
 
-      - name: Attach artifacts to ${{ env.iota_tag }} release in GH
-        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
-        with:
-          tag_name: ${{ env.iota_tag }}
-          files: |
-            ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz
+  #     - name: Attach artifacts to ${{ env.iota_tag }} release in GH
+  #       uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
+  #       with:
+  #         tag_name: ${{ env.iota_tag }}
+  #         files: |
+  #           ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz
 
   update-homebrew-formula:
     name: Run brew bump-formula-pr for iota on testnet releases
-    needs: release-build
+    # needs: release-build
     runs-on: ubuntu-latest
     # releasing iota cli on testnet releases because it lags `main` less than mainnet, but is more likely to be stable than devnet
     if: ${{ contains( inputs.iota_tag, 'testnet') || contains( github.ref, 'testnet') }}
