chore(ci): disable split-cluster mainnet

diff --git a/.github/workflows/split_cluster.yml b/.github/workflows/split_cluster.yml
--- a/.github/workflows/split_cluster.yml
+++ b/.github/workflows/split_cluster.yml
@@ -5,39 +5,39 @@ on:
     types: [opened, synchronize, reopened, ready_for_review]
   push:
     branches:
-      - main
+      - develop
 
 jobs:
-  validate-mainnet:
-    if: github.event.pull_request.draft == false
-    runs-on: self-hosted
-    steps:
-      - name: checkout code repository
-        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
-        with:
-          fetch-depth: 0
-      - name: Run split cluster check script
-        id: mn-split-cluster-check
-        continue-on-error: true # if failure, continue to bisect
-        run: |
-          IOTA_PROTOCOL_CONFIG_CHAIN_OVERRIDE=mainnet \
-          scripts/compatibility/split-cluster-check.sh origin/mainnet ${{ github.sha }}
-      - name: Bisect
-        if: steps.mn-split-cluster-check.outcome == 'failure' && github.event_name == 'push'
-        run: |
-          git bisect start ${{ github.event.pull_request.head.sha }} origin/mainnet
-          IOTA_PROTOCOL_CONFIG_CHAIN_OVERRIDE=mainnet \
-          git bisect run scripts/split-cluster-check.sh origin/mainnet ${{ github.sha }}
-          git bisect reset
-      - name: Mark Failures
-        if: failure()
-        run: exit 1
+  # validate-mainnet:
+  #   if: github.event.pull_request.draft == false
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Checkout code repository
+  #       uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Run split cluster check script
+  #       id: mn-split-cluster-check
+  #       continue-on-error: true # if failure, continue to bisect
+  #       run: |
+  #         IOTA_PROTOCOL_CONFIG_CHAIN_OVERRIDE=mainnet \
+  #         scripts/compatibility/split-cluster-check.sh origin/mainnet ${{ github.sha }}
+  #     - name: Bisect
+  #       if: steps.mn-split-cluster-check.outcome == 'failure' && github.event_name == 'push'
+  #       run: |
+  #         git bisect start ${{ github.event.pull_request.head.sha }} origin/mainnet
+  #         IOTA_PROTOCOL_CONFIG_CHAIN_OVERRIDE=mainnet \
+  #         git bisect run scripts/split-cluster-check.sh origin/mainnet ${{ github.sha }}
+  #         git bisect reset
+  #     - name: Mark Failures
+  #       if: failure()
+  #       run: exit 1
 
   validate-testnet:
     if: github.event.pull_request.draft == false
     runs-on: self-hosted
     steps:
-      - name: checkout code repository
+      - name: Checkout code repository
         uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
         with:
           fetch-depth: 0
